title: p3
#email: your-email@example.com
description: >- 
  "hashNetwork" does not own, host, or store any files on our platform. We solely provide links to content available on external sites. Users are required to delete any downloaded content within 48 hours and are encouraged to purchase legal copies to support artists and creators. "hashNetwork" strongly advocates for the legitimate acquisition of content.


  "hashNetwork" bears no responsibility for content accessed through external links. Our service is intended exclusively for lawful preview purposes.

  By using "hashNetwork", you acknowledge and agree to comply with all applicable intellectual property laws and regulations.

url: "/"  # For local testing
#baseurl: "/audio"  # This is crucial for testing locally in a subdirectory

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination settings
paginate: 10
paginate_path: "/page/:num/"

permalink: pretty

collections:
  artists:
    output: true
    permalink: /artists/:title/
include:
  - search.json.liquid

defaults:
  - scope:
      path: "search.json.liquid"
    values:
      permalink: /search.json
